[package]
name = "tidyup"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["src/messages"]

[profile.release]
panic = "abort"

[dependencies]
messages = { version = "0.1.0", path = "src/messages" }
nix = "0.25.0"
serde = { version = "1.0.147", features = ["derive"] }
